### ISSUE TITLE
Feature Request: Rings

### ISSUE THREAD

**Issue by K4N0** [TehNut-Mods/RedstoneArmory#20]
.

**Comment by SgtPunishment** [comment]
Why would a ring do all of these effects? It makes logically no sense what so ever, I would suggest you talk to RFTools, this mod IMO isn't the place for those kind of suggestions

**Comment by Badcholo** [comment]
Sorry for my quick suggestion. I meant different rings for different effects. I saw that you used baubles and was just suggesting more uses for it. suggestions can be placed anywhere. We don't need to be rude about it. If you don't like it, it's fine, it was just a suggestion. I see why the issues here is empty. Thanks for the mod, but besides a use for the necklace capacitor which just saves you a hot-bar slot. This mod is just a very expensive upgrade without very much results. The Armor still takes fall damage. The pickaxe and tools speed increase is not much faster. Making it any faster may be called Cheaty. Most mods now have jet-packs. Except for the amusing potato armor I don't see much use for this mod. Since we are being honest and telling it like it is. There you go. Ps, the pickaxe teleport killed me a bunch of times, what is that useful for? suffocating yourself? yes i removed the teleport fromt he config.

**Comment by SgtPunishment** [comment]
You do realise I have nothing to do with this mod? I'm not a part of the time, I'm just another user

On 7 May 2015, at 16:41, Badcholo notifications@github.com wrote:

Sorry for my quick suggestion. I meant different rings for different effects. I saw that you used baubles and was just suggesting more uses for it. suggestions can be placed anywhere. We don't need to be rude about it. If you don't like it, it's fine, it was just a suggestion. I see why the issues here is empty. Thanks for the mod, but besides a use for the necklace capacitor which just saves you a hot-bar slot. This mod is just a very expensive upgrade without very much results. The Armor still takes fall damage. The pickaxe and tools speed increase is not much faster. Making it any faster may be called Cheaty. Most mods now have jet-packs. Except for the amusing potato armor I don't see much use for this mod. Since we are being honest and telling it like it is. There you go. Ps, the pickaxe teleport killed me a bunch of times, what is that useful for? suffocating yourself? yes i removed the teleport fromt he config.

**Comment by Badcholo** [comment]
why do you reply to other users issues ya tard? omfg your just a troll.

**Comment by SgtPunishment** [comment]
It's called freedom of speech, I'm voicing my opinions on features you've suggested, and please do not use that kind of language (tard) as that is very offensive

On 7 May 2015, at 16:47, Badcholo notifications@github.com wrote:

why do you reply to other users issues ya tard? omfg your just a troll.

**Comment by Badcholo** [comment]
We post on here to speak with mod authors not to trolls. I dont care about your opinions so keep it to yourself.

**Comment by Tombenpotter** [comment]
No. Just so that you are aware, all the suggestions were discarded because you were a jerk. Have a nice day :)

**Comment by TehNut** [comment]
Just some final notes:

> This mod is just a very expensive upgrade without very much results. The Armor still takes fall damage. 

It provides 95% damage reduction which is quite a bit higher than the Redstone Arsenal armor. It's meant to be a direct upgrade. Fire is unblockable damage. The armor does not do anything against that. Same goes for fall damage. And, wouldn't you know, **NEITHER DOES REDSTONE ARSENAL**.

> Most mods now have jet-packs.

And? Not every mod needs every feature another mod adds. It's boring that way.

> Ps, the pickaxe teleport killed me a bunch of times, what is that useful for? suffocating yourself? yes i removed the teleport fromt he config.

Stand closer to the wall. The blocks _always_ teleport back the same amount. It also only happens when you empower the tool. Disabling in the config just removes the only thing the empowering does.

> We post on here to speak with mod authors not to trolls. I dont care about your opinions so keep it to yourself.

@SgtPunishment is no troll. I talk to him on a regular basis and we had a conversation about the _exact_ things he said.

> I dont care about your opinions so keep it to yourself.

Isn't that what feature request issues are for? People giving opinions on ideas?
